server:
  port: 9001
spring:
  application:
    name: service1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.253.130:3306/zh?useEncode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:

  cloud:
    #nacos设置
    nacos:
      discovery:
        server-addr: 192.168.253.130:8848
      config:
        server-addr: 192.168.253.130:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: zh.dao.mapper
